### ISSUE TITLE
ERROR: certificate verification

### ISSUE THREAD

**Issue by chenkangjun** [ESGF/esg-publisher#101]
(esgf-pub) [root@esg ~]# python /usr/local/esgf-node-manager/src/python/client/fetch-pub-credentials.py esgf-node.llnl.gov
ERROR!

{ 'ERROR': 'certificate verification' , 'Message': [Errno 2] No such file or directory: '/etc/grid-security/certificates/c6645765.0'}

Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

**Comment by sashakames** [comment]
This was a server side error and has been corrected.  Please try again.  If you still cannot get the credentials automatically, they are posted at this page (you'll need to request an account from Renata McCoy <mccoy20@llnl.gov>)

https://acme-climate.atlassian.net/wiki/spaces/ESGF/pages/369983978/RabbitMQ+server+config

**Comment by chenkangjun** [comment]
I still cannot get the credentials, error is
-----------------------------
python /usr/local/esgf-node-manager/src/python/client/fetch-pub-credentials.py esgf-node.llnl.gov
ERROR!

<h1>Server Error (500)</h1>

No JSON object could be decoded
----------------------------
I go to apply for an account first.

**Comment by sashakames** [comment]
Not a publisher error
