### ISSUE TITLE
esgtest_publish -help shows incorrect command in the "Usage" message.

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esg-publisher#102]
# esgtest_publish --help
Allow anonymous logging usage to help improve UV-CDAT(you can also set the environment variable UVCDAT_ANONYMOUS_LOG to yes or no)? [yes]/no: no 
option --help not recognized
Usage:
    esg_testpublication [options]

        Test Publication:
            - Set up a myproxy certificate
            - Generate a mapfile
            - Publish and unpublish a dataset
            - Verify each step

**Comment by sashakames** [comment]
Fixed in 45db3ea
