### ISSUE TITLE
make service fileservice a default?

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#109]
If there is enough reason not to, we can leave as is.  Often a point of error to omit by mistake.  One could then override with particular services.  perhaps time to refactor the "--service" option

**Comment by alaniwi** [comment]
I'd agree with making it a default - with suitable notice to node managers.

**Comment by alaniwi** [comment]
But if `--service` is specified at all, then it ought to override that default completely.

**Comment by sashakames** [comment]
looks like done
