### ISSUE TITLE
update cdf2cim dependency

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esg-publisher#130]
https://github.com/ESGF/esg-publisher/blob/6b429430176e583468fd9887825afdd170b36267/src/python/esgcet/requirements.txt#L9

According to @davidhassell, a required bugfix is available in v0.3.0.

(More details in email thread on CDNOT list with subject "ValueError: Can't create date-time array from units <CF Units: no parent>".)

**Comment by alaniwi** [comment]
cdf2cim now on 0.3.2.0 (and further update imminent?) Dependency in `requirements.txt` still says 0.2.2.1.

**Comment by davidhassell** [comment]
Yes - latest version of cdf2cim should be being used. Currently on 0.3.2.0. with a bug-fixed 0.3.3.0 due soon (today, possibly).

**Comment by sashakames** [comment]
Not sure where requirements.txt is being used.  For instance the SQLAlchemy range specifies a limited old range (FWIW 1.3.0 seems to be incompatible with esginitialize -c)
Any due for an update of many packages
