### ISSUE TITLE
Omitting "branch_method" raises error in publisher.

### ISSUE THREAD

**Issue by tinoue70** [ESGF/esg-publisher#132]
In the latest version of the document "CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV's"  (https://goo.gl/v1drZl), an attribute "branch_method" can be omitted if no parent, but a datafile without this attribute raises error in esgpublish (Version: v2.7.1-master-release).

See [this](https://github.com/ESGF/esg-publisher/files/2674847/message.txt) for error log.

This datafile is created using CMOR3.

It seems that "extract_global_attrs" in esg.cmip6.ini contains "branch_method" as one of its values is the reason why.

At momemt, we decided to set "branch_method" to "no parent” explicitly, but either the document or the implementation of esgpublish should be fixed.

**Comment by sashakames** [comment]
We have updated the cmip6 ini file to no longer require branch_method.  Please update using esgfetchini
