### ISSUE TITLE
CMIP6Handler.validateFile() only call when handler instantiation

### ISSUE THREAD

**Issue by glevava** [ESGF/esg-publisher#138]
PrePARE seems to be called during publication *only* for the first file of a dataset
In the example below, PrePARE CV check is successful for one file only (the first one) of the dataset. Nothing printed for the other files.
When I run PrePARE as a standalone, the 3 files of the dataset are properly checked.
And the mapfile has 3 files as properly processed by the `extractFromDataset` method then.
```
$ esgpublish --project cmip6 --service fileservice --map in_publishing/CMIP6.CMIP.IPSL.IPSL-CM6A-LR.historical.r10i1p1f1.3hr.hfss.gr.v20180803.map
INFO       2018-12-19 15:50:15,654 Created PID connector.
INFO: for dataset ID CMIP6.CMIP.IPSL.IPSL-CM6A-LR.historical.r10i1p1f1.3hr.hfss.gr,
      [.... cdf2cim stuff...]
     :: CV SUCCESS :: [...]hfss_3hr_IPSL-CM6A-LR_historical_r10i1p1f1_gr_185001010130-194912312230.nc
INFO       2018-12-19 15:50:20,592 Replacing files in dataset: CMIP6.CMIP.IPSL.IPSL-CM6A-LR.historical.r10i1p1f1.3hr.hfss.gr, version 20180803
INFO       2018-12-19 15:50:25,147 File [...]hfss_3hr_IPSL-CM6A-LR_historical_r10i1p1f1_gr_185001010130-194912312230.nc exists, skipping
INFO       2018-12-19 15:50:25,155 File [...]hfss_3hr_IPSL-CM6A-LR_historical_r10i1p1f1_gr_195001010130-195912312230.nc exists, skipping
INFO       2018-12-19 15:50:25,162 File [...]hfss_3hr_IPSL-CM6A-LR_historical_r10i1p1f1_gr_196001010130-201412312230.nc exists, skipping
INFO       2018-12-19 15:50:25,162 Adding file info to database
```
This is the same for a new dataset which was not in the db before.
PrePARE is called in the `validateFile` method of the `cmip6_handler.py` but this method is called during handler instanciation only.

**Comment by sashakames** [comment]
I can reproduce the issue going back to v3.4.9  - I'm not sure if earlier versions will work because we had fixed issues in loading the correct Tables and CV pairing.

**Comment by sashakames** [comment]
also v3.4.2  - I wonder if we all missed this with multi-file datasets
, and this has been a bug all along....

**Comment by sashakames** [comment]
Required additional corrections, v3.5.9
