### ISSUE TITLE
version mismatch between release tag (3.5.9) and in __init__.py (3.5.8)

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esg-publisher#142]
Version in `esgcet/__init__.py` in 3.5.9 says 3.5.8. This leads to wrong version reported by `pip freeze` etc.
See: https://github.com/ESGF/esg-publisher/blob/v3.5.9/src/python/esgcet/esgcet/__init__.py

**Comment by sashakames** [comment]
They are in essence equivalent.  3.5.9 was released when Guillaume was struggling with both 3.5.7 and 3.5.8 and there was some concern he couldn't get a particular bug fix.  That said, we can release 3.5.10 just to correct the inaccuracy and address the missing IntegrityError issue.

**Comment by alaniwi** [comment]
It _might_ be worth setting the correct version number in setup.py and retagging, but I agree that once it is no longer the current release it is less likely to be an issue.
