### ISSUE TITLE
Augment CMIP6 publisher to test to valid activity_id registration

### ISSUE THREAD

**Issue by durack1** [ESGF/esg-publisher#156]
We've hit some problems where valid and registered `source_id` entries are publishing data for an `activity_id` in which they have not registered an intention to contribute (the `activity_participation` fields in [CMIP6_source_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L3-L6)). Such publications should not be allowed, as it causes problems downstream as the other services (particularly the DKRZ citation service) rely on valid registered details.

Some recent cleaning up has been required after the fact, whereas ideally, it would be best to block publication UNTIL the registered `source_id` details are amended appropriately.

For ref:
WCRP-CMIP/CMIP6_CVs#900
WCRP-CMIP/CMIP6_CVs#923

Ping @MartinaSt @taylor13 @sashakames

**Comment by sashakames** [comment]
While I think this should be part of pre-publication QA - and any reference workflows should prevent publishing, we should incorporate this requirement into the next-gen server-side API "QA", meaning that the index can reject publications that fail to meet certain criteria.

**Comment by durack1** [comment]
@sashakames thanks for chiming in. As this will be an ongoing issue for CMIP6, it would be really helpful if we could implement this check as soon as possible. Having said that, if remote ESGF nodes don't plan to update their publisher stack, then such changes won't solve the ongoing issues we're hitting with existing publications

Not sure how best to proceed here to minimize the cleanup steps

**Comment by sashakames** [comment]
Don't get me wrong, I'm interested in "fast tracking" this work, and therefore a publisher to meet the needs of ongoing CMIP6 publishing.  However, there are several inter-dependencies to consider in releasing a new publisher.  I can keep everyone updated with a roadmap.  What I envision now is a replacement command line, but for now might be specific for CMIP6, other projects may need to work themselves with sub-modules.
