### ISSUE TITLE
Migrate esg.ini settings to simpler form

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#159]
There are too many obsolete settings that don't need migration.  We are down to many fewer, 
eg. data_node, index_node, certificate.
log_level (eg. debug)

**Comment by alaniwi** [comment]
It would be worth circulating a list of settings that you propose to withdraw, in case anybody votes to keep particular ones. (Sorry if you've already done this and I've missed it.)

**Comment by sashakames** [comment]
Not done yet.  Sure, I'll post the list here for comment.

**Comment by sashakames** [comment]
settings are now .yaml
