### ISSUE TITLE
about esgpublish thredds_dataset_roots

### ISSUE THREAD

**Issue by lamaliang** [ESGF/esg-publisher#160]
Hello 

I need to upload the CMIP6 data. And I had change thredds_dataset_roots path in esg.ini. But it still point the previous the path. I had found almost file. I could not fix the problem. 

And only some data have this problem, another data can upload to server.  

The error message as following :
File : XXXXXXX/XXXXX.nc  is not contained in any THREDDS root path. Please add an entry to thredds_dataset_roots in the configuration file.

**Comment by sashakames** [comment]
hi @lamaliang 
could you please copy your  `thredds_dataset_roots` entry ? double check the file for typos.

We are updating the publisher software to a completely new version, stay tuned!

**Comment by lamaliang** [comment]
Sorry, I am late for reply the message. I had use more method to upload the data. only upload our historical 3-houly data is error. So I just so confuse.
