### ISSUE TITLE
mapfile input for esgpublish command

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#161]
(1) if --map is not specified, the positional argument(s) following the "named" arguments can specify the mapfile(s)
(2) no mapfile, could be stdin ?
(3)  mapfile(s) should be checked "isdir()" if a directory then process the contents as a list of directories
(4) --mapfile-list <fn> can be used instead for a list of mapfiles ; --mapfile-list - allows a list from stdin

**Comment by sashakames** [comment]
- [ ] don't assume that we have a .map extension, glean from parsing first line.

**Comment by lisi-w** [comment]
Doesn't rely on .map extension any more, implemented handling of directories containing mapfiles which can be passed as well. We discussed --mapfile-list would over complicate, and given that users can submit either a list of files on the command line following --map, a list of files containing paths to mapfiles, or directories of mapfiles it seems that stdin would not be necessary for client use.

**Comment by sashakames** [comment]
For testing: document the tests, put into a shell script so we can reproduce

**Comment by lisi-w** [comment]
Tested; current supported mapfile inputs: mapfile, list of mapfiles, text file containing a list of absolute mapfile paths, a list of such text files, a directory containing mapfiles, or a list of directories containing mapfiles. (Note: list refers to multiple on the command line, i.e., --map file.map file.map, or --map /my/maps1/ /my/maps2/ etc.) 

Bash script to test is in /export/witham3/test-suite on greyworm.
