### ISSUE TITLE
add command-line argument for path to ini directory in new publisher

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esg-publisher#163]
According to https://esg-publisher.readthedocs.io/en/gen-five-pkg/esgpublish.html#usage , there doesn't seem to be an equivalent of the existing `-i init_dir` option.

Please can we have a command-line option to point to the config directory (or equivalent), so that a single publisher installation can be used with a choice of configurations.

**Comment by lisi-w** [comment]
This has been implemented, the new command line options are:

**Comment by lisi-w** [comment]
More info about the esgmigrate command can be found here: https://esg-publisher.readthedocs.io/en/gen-five-pkg/esgmigrate.html
