### ISSUE TITLE
Add a version argument

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#164]
(test2) [ames4@esgf-test-data ~]$ esgpublish --version
usage: esgpublish [-h] [--test] [--set-replica] [--no-replica] [--esgmigrate] [--json JSON]
                  [--data-node DATA_NODE] [--index-node INDEX_NODE] [--certificate CERT]
                  [--project PROJ] [--cmor-tables CMOR_PATH] [--autocurator AUTOCURATOR_PATH] --map
                  MAP [MAP ...] [--ini CFG] [--silent] [--verbose]
esgpublish: error: the following arguments are required: --map

**Comment by sashakames** [comment]
Version is in recipe/meta.yml and setup.py.  should be from one central location, maybe meta.yml should be a template?

**Comment by lisi-w** [comment]
The Makefile obtains the version for the conda recipe like so: 
`version=$(shell git describe --tags | cut -c 1-7 )`
This is then replaced using sed commands (same with branch which can be defined as an argument for the Makefile):
`sed_v = s/VERSION/$(version)/
sed_b = s/BRANCH/$(branch)/g`
which is later used:
`sed -i "$(sed_v)" $(WORKDIR)/esg-publisher-feedstock/recipe/meta.yaml
sed -i "$(sed_b)" $(WORKDIR)/esg-publisher-feedstock/recipe/meta.yaml`

I should have caught this when pulling in the latest commit, but meta.yaml is supposed to be a template, the latest commit changed and hard coded version and branch
` - version: VERSION
  + version: 5.0.0a3`
But that should be fixed now.

**Comment by lisi-w** [comment]
Do you mean that we should have a version for the dataset? I fixed the hard coded version in the meta.yaml, but if a user wants to change the version on a dataset that can be accomplished using the --json option I believe.

**Comment by sashakames** [comment]
correct `--version` refers to the  VERSION of the software package.  Just a standard flag.   You could `conda list | grep esgcet` but everyone just remembers the flag

The sed approach is good for the Makefile .

```
from importlib.metadata import version 
version('esgcet')
```
