### ISSUE TITLE
esgunpublish

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#167]
esgunpublish is missing from setup.py  
(1) derived from unpublish.py
(2) Needs integration with config settings, now uses settings.py
(3) See PR with several fixes
(4) consider argparse so can pass data_node, index_node, .etc in addition to '--delete' optional argument

**Comment by sashakames** [comment]
https://github.com/lisi-w/esg-publisher/pull/5
(1) above done

**Comment by sashakames** [comment]
Update, the PR should now cover setup.py.  I was able to run `esgunpublish` after an install.   The API always returns success even if the dataset is bogus.

**Comment by lisi-w** [comment]
The command is functional. I'll add docs to explain how it works soon.
