### ISSUE TITLE
Major refactor

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#169]
## This is an epic issue, we may decompose into smaller tasks:

- [x] mk_dataset refactor:  The functionality in this module is 
     - [x] Decompose the functionality into smaller pieces.
    1. express these pieces as generic functions
    1. implement the specific functions
     - [x] create classes of mk_dataset for various projects
     - [x] support custom project DRS loaded from the config file
- [x]  pub_internal refactor
     - [x] make this an object with generic functions
     - [x] implement classes for projects.  the class methods call mk_dataset and other modules.
- [x] Make an architecture diagram for this design.  
- [x] comprehensive test suite to exercise options, maybe automate, some unit testing

### Minor details
- [x] setting/option for verify=True/False
- [x] cleanup output, make consistent: Error, WARNING, INFO, etc for what gets output in the  3 modes.
- [x] refactor _init__() and use super().__init__() for common attributes.

**Comment by lisi-w** [comment]
pub_internal has been refactored for a more object oriented approach, currently works for cmip6, future projects will be added once we finalize design
code for prototype version can be found in the refactor branch

**Comment by sashakames** [comment]
example code:
https://github.com/lisi-w/esg-publisher/blob/refactor/pkg/esgcet/cmip6.py
I'd suggest we need a base class from which cmip6 is derived.

**Comment by lisi-w** [comment]
Further publisher features/testing are covered in other cards/issues. The publisher is fully refactored, but we can reopen this if the need arises.
