### ISSUE TITLE
add primavera support

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esg-publisher#198]
Trying to publish a PRIMAVERA dataset, using:

```
$ esgpublish -i /path/to/esg.ini --cert /path/to/certificate-file --map /path/to/PRIMAVERA.primWP5.CNRM-CERFACS.CNRM-CM6-1.primWP5-amv-neg.r10i1p1f2.SIday.sitimefrac.gn.v20190320.map --no-replica
```
I get:
```
2022-09-20 11:54:13 ERROR    Project primavera not supported.
Open an issue on our github to request additional project support.
```

Looking in one of the data files, it has global attribute:
```
                :mip_era = "PRIMAVERA" ;
```

I don't know if case is relevant (note the lower-case "primavera" in the error message), but I can't see anywhere in the input that the lower-case name would come from, no occurrence of it in the file metadata.

**Comment by sashakames** [comment]
@alaniwi  You'll need to add the following to your esg.ini:

user_project_config = { "primavera": { "DRS": ["mip_era", "activity_id", .. ], "CONST_ATTR": [ "attr": "my_attr", ] } }

Try the lowercase version for now (I think we adopted the convention that project names would be lower).  

For DRS, complete the DRS path entries (I think this the same as CMIP6.  If there are any "constant" attributes for all datasets that should be assigned you can create these under "CONST_ATTR" .  If not, you can either remove it or try an empty list for the value.   
This feature hasn't been thoroughly tested, but looks like we need to give it some attention now, and so I'm happy to work with you on it.

**Comment by sashakames** [comment]
Task to update the esg-publisher documentation to be clear how to add projects.

**Comment by alaniwi** [comment]
Thanks.  It wants to publish it using upper case.

If I put lower case name in the config file (per your example above), then it doesn't find it. ("Error: Project {project} Data Record Syntax (DRS) not defined. Define in esg.ini", and I can see that this comes from `pkg/esgcet/mk_dataset.py`.)

I can get it to publish using an upper-case name for the project in the config file:
```
user_project_config = { "PRIMAVERA": { "DRS": ["mip_era", "activity_drs", "institution_id", "source_id", "experiment_id", "member_id", "table_id", "variable_id", "grid_label"], "CONST_ATTR": [ ] } }
```

However, then it ends up with `project=PRIMAVERA` in the published metadata.  As datasets that we published with the old publisher ended up with `project=primavera`, I would much prefer to be consistent (or otherwise it will complicate things for users when they search).  Any advice on this please?

**Comment by jonseddon** [comment]
@alaniwi I think that this problem was actually caused by a metadata fault in my source files. I'm just writing an email to you currently about it.

**Comment by sashakames** [comment]
@alaniwi I agree that we should try to be consistent.  with the CMIP* we had been using UPPER for 5 & 6.  Anyway, I glad it least my initial suggestion worked.  I wonder if you try to set { "CONST_ATTR" : {"project" : "primavera" } would it overwrite the project?  If not, I think that should be the solution for legacy projects, and we come to some agreement for the standard for future projects.
I see the published data and so I can capture that to create a test case in case I need to patch the code for you.

**Comment by alaniwi** [comment]
I've seen @jonseddon's comment above, and related email, about a problem with those datasets having the wrong `mip_era` value in the netCDF metadata, but this turns out to be an independent problem, so I still need to address this one.  (In any case, it seems that because the `mip_era` facet is part of the dataset ID, the publisher takes the value from the dataset ID rather than the file metadata, so it wouldn't end up affecting the published record.)

Looking at the code in `mk_dataset.py`, it looks like the publisher takes the first part of the dataset ID:

https://github.com/ESGF/esg-publisher/blob/59143514092ef074e258e364a8f0eaec04e89401/pkg/esgcet/mk_dataset.py#L89-L91

and then (inside `init_project`) converts it to lower-case if it is _not_ a user-defined project -- but this one _is_ user-defined:

https://github.com/ESGF/esg-publisher/blob/59143514092ef074e258e364a8f0eaec04e89401/pkg/esgcet/mk_dataset.py#L18-L19

But in any case, this is the default and it seems that it can be overridden by calling `set_project`.  On further inspection of the code I concluded that this happens when the explicit command line option `--project` is used, but that there doesn't seem to be any way to put a mapping into the new-style ini file that would make that happen -- whereas with the old publisher, we had this in `esg.ini`:
```
category_defaults =
    project | primavera
```
@sashakames Please correct me if I have missed some supported functionality in the publisher.  But otherwise, that's okay, I can add some functionality to our calling code to add extra publisher command-line options when processing PRIMAVERA data. I can see how this can be done in a reasonably generic way, but here is not the place to go into details on that.

**Comment by sashakames** [comment]
@alaniwi  Sounds like you have a means to handle this for PRIMAVERA in the meantime.  
Alternatively you can use the `esg-search/ws/update` API to correct the project attribute for PRIMAVERA datasets to set to `primavera` as a workaround.   I'll work on ensuring that it can be set by reordering the application of the `CONST_ATTR` values so a `project` can be applied for any arbitrary case.  

We used `lower()` to be consistent with use of lower in project keys in the old convention for esg.<project>.ini

**Comment by alaniwi** [comment]
Hi @sashakames, I have now got our publication workflow system to be able to pass different command line args to the publisher for different projects, so for the PRIMAVERA data it can now publish with `--project primavera` (as needed to prevent it from making a wrong assumption based on the dataset ID).  However, there is a separate issue with PRIMAVERA for us at present.

Currently, I am using the following:
```
user_project_config = { "primavera": { "DRS": ["mip_era", "activity_drs", "institution_id", "source_id", "experiment_id", "member_id", "table_id", "variable_id", "grid_label"], "CONST_ATTR": [ ] }, "CMIP6": { "DRS": ["mip_era", "activity_drs", "institution_id", "source_id", "experiment_id", "member_id", "table_id", "variable_id", "grid_label"], "CONST_ATTR": [ ] } }
```

 - (As an aside in case you're wondering, the reason for putting `'CMIP6'` in there as a key alongside `'primavera'` is that CMIP6 publication will fail if the key is not present and also the `user_project_config` is set to anything, although it will work fine if `user_project_config` does not exist at all.)

The problem that I now have is that it seems to treat PRIMAVERA as a generic project, meaning that it does not set a number of dataset metadata items that are set for CMIP6, in particular the following:

activity_id, data_specs_version, experiment_title, frequency, grid, nominal_resolution, pid, product, realm, source_type, variant_label

Do you know how to configure it so that these are populated please?  I see that there are various dictionaries defined in settings.py for CMIP6:

https://github.com/ESGF/esg-publisher/blob/59143514092ef074e258e364a8f0eaec04e89401/gen-five/src/python/settings.py#L14-L30

so essentially the question is what can I put in the ini file to make it behave as if these various dictionaries in the code (`GA` etc as above) also contained sub-dictionaries for `'primavera'` alongside the `'CMIP6'` ones.

I haven't tried editing the `settings.py` inside the conda environment - it feels like something I shouldn't be doing because it is part of the software rather than user configuration.  (It would also be difficult to maintain any such changes if we update the installed publisher version.)

Many thanks

**Comment by alaniwi** [comment]
If I grep the code for `CONST_ATTR`, I see that there is code to allow taking the values from the config file rather than use the hard-coded value:

https://github.com/ESGF/esg-publisher/blob/59143514092ef074e258e364a8f0eaec04e89401/pkg/esgcet/mk_dataset.py#L21-L28

but I can't see anything like it for the others (`GA`, `GA_MAPPED`, `GA_DELIMITED`) -- they only exist as variable names in the code, not as string values that might get used as a dictionary key anywhere

**Comment by sashakames** [comment]
@alaniwi  I don't think it should be that hard to extend the use of the GA extraction to user-defined projects.  Alternatively it might be useful to allow for "clone" projects, namely user-defined but resemble an existing project like CMIP6.  I think we may need this for CMIP6+.   In the short term I'd want to deliver something that makes the most sense for Primavera as you need that now.

**Comment by alaniwi** [comment]
Thanks. Clone might have a possible usability advantage that you just need to define your project as an appropriate clone and then not have to configure all of the details of the individual facets, but for now I am happy to do whatever is easiest to support.

**Comment by alaniwi** [comment]
A couple of related pull requests:
  - I see this from @sashakames https://github.com/ESGF/esg-publisher/pull/200
  - On top of that, there is this from me: https://github.com/ESGF/esg-publisher/pull/201

The latter has Sasha's branch as its base branch, so depending on the order of merging, this might need to be changed.
