### ISSUE TITLE
ESGPublishError: the THREDDS Data Server Unavailable?

### ISSUE THREAD

**Issue by tiantdk** [ESGF/esg-publisher#211]
**esgpublish --service fileservice --map /esg/mapfiles/$exp --project cmip6 --noscan --thredds**
Traceback (most recent call last):
  File "/usr/local/conda/envs/esgf-pub/bin/esgpublish", line 783, in <module>
    main(sys.argv[1:])
  File "/usr/local/conda/envs/esgf-pub/bin/esgpublish", line 689, in main
    result = reinitializeThredds()
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet/publish/thredds.py", line 1177, in reinitializeThredds
    raise ESGPublishError("Error reinitializing the THREDDS Data Server. Result=%s"%`reinitResult`)
esgcet.exceptions.ESGPublishError: 
"**Error reinitializing the THREDDS Data Server.** Result='<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>503 Service Unavailable...The server is temporarily unable to service your\n request due to maintenance downtime or capacity\nproblems. Please try again later..."

It is true? How could I know when the downtime is over?

**Comment by sashakames** [comment]
Hi @tiantdk  This would be your local THREDDS server on your data node, so you may need to contact your system administrator.  I recommend upgrading the publisher so you can avoid this sort of problem, the recent versions do not require THREDDS catalogs.  
https://esg-publisher.readthedocs.io/en/latest/index.html

**Comment by sashakames** [comment]
@tiantdk  Are there still issues here?  Can we close this issue?

**Comment by tiantdk** [comment]
> @tiantdk Are there still issues here? Can we close this issue?

Yes. We are about to upgrade the publisher in the future.
