### ISSUE TITLE
Documentation on generatl installation and configuration needs update and further explication

### ISSUE THREAD

**Issue by TonyB9000** [ESGF/esg-publisher#240]
Several issues in documentation need to be addressed.

Some elements of the configuation need explanation in order to be useful:

- Autocurator (and autoc_path) are now optional, but the  documentation still says it is required.
- data_roots:  The doc says "paths where you place your project data for publication", but in fact the actual data_node paths can be different.  The data_roots listed MUST be any paths local to esgpublish execution where the  files subject to publication can be accessed during the publication process.  It should be made clear that these need not coincide.
- Perhaps we need both "publication_data_roots" and "local_data_roots" if different than the former.
- Cert:  Has the default changes to {Optional]?
- Test mode:  A flag to toggle test more explains to override default "false" if not doing production publication.  But there is no description of what difference it will make and where.  Is it a "dry-run" where output logs tell if everything was OK?
- Set_Replica:  (Optional) Enable or disable replica publication settings. Default assumes False.  But nothing here explains the implications of "replica publication".  What difference does it make?  If you publish without it, can you simply toggle it "on" later, or must you republish?

If there exists further explanation of these terms or settings elsewhere in the documentation, those locations or links should be included here.

**Comment by sashakames** [comment]
Appears that several of these were already completed in the v5.2.3 docs:
https://esg-publisher.readthedocs.io/en/main/install.html#config-file-esg-yaml

**Comment by TonyB9000** [comment]
@sashakames 

**Autocurator:**  Under Installation:Conda & Required Packages, it says:

`NOTE: you will need a functioning version of autocurator in order to run the publisher, `

This is not true.

**Config File (esg.yaml)**

**Data Node and Data Roots:**  These should be placed together IMHO.  Also, there are TWO separate places where "paths to the data" exist.  One is in the manifest (mapfile), and one is the "Data Roots".  Thanks to Argonne, these need not be the same.  The "Data Roots" paths need not be accessible to esgpublish at publication time, whereas the paths supplied in the mapfile must be.

Also, for acme1, I have a working "data_root": ` /p/user_pub/work: user_pub_work`.  Note that it consists of:

- a path section ("/p/user_pub/work: user_pub_work")
- another section ("user_pub_work")

and nowhere (that I can find) is the application of these separate parts explained.  The only explanation given is "Each entry maps the path to a logical subdirectory within a data url on the datanode".  I might guess that "user_pub_work" is the "logical subdirectory within a data url", but the details of the construction are fuzzy to me (and where "https_url" is concerned, I don't know that this is even employed anymore.

**set_replica:** The explanation here says:

`Enable or disable replica publication settings. Default assumes False, or replica publication off.`

That explanation strongly implies that setting it to "true" will "enable replica publication".  But i an earlier email, you explained that changing this would not trigger anything - as it it were merely informative (as in, "this publication is a replica" versus "this publication is original").  So, I remain confused in the intent of this setting.

**Comment by sashakames** [comment]
Documentation updated for the `v5.2.4` release just now. Note that we are in a quiet period for most sites between CMIP6 and CMIP7 phases.   We will have additional resources to deliver the necessary documentation when more groups resume publishing.
