### ISSUE TITLE
publisher installation does not copy eggs properly

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esg-publisher#39]
When I try to install the publisher version v3.0.1, it leaves several of the egg files being pointed to in the temporary build directory rather than copied into `site-packages`.

Here are the contents of `/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/easy-install.pth` after I did `python setup.py install` in `/tmp/esg-publisher/src/python/esgcet` containing a clone of the repo in which `v3.0.1` had been checked out:

```
import sys; sys.__plen = len(sys.path)
./pip-1.2.1-py2.7.egg
./six-1.9.0-py2.7.egg
./MyProxyClient-1.3.0-py2.7.egg
./setuptools-18.8.1-py2.7.egg
./esgf_node_manager-0.1.5-py2.7.egg
./esgf_dashboard-0.0.1-py2.7.egg
./esgcet-3.0.1-py2.7.egg
/tmp/esg-publisher/src/python/esgcet/.eggs/esgprep-2.6.2-py2.7.egg
/tmp/esg-publisher/src/python/esgcet/.eggs/uritemplate.py-2.0.0-py2.7.egg
/tmp/esg-publisher/src/python/esgcet/.eggs/github3.py-0.9.5-py2.7.egg
/tmp/esg-publisher/src/python/esgcet/.eggs/lockfile-0.12.2-py2.7.egg
import sys; new = sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p = getattr(sys, '__egginsert', 0); sys.path[p:p] = new; sys.__egginsert = p + len(new)
```
Note the lines starting `/tmp/`...

As a result, `esgpublish` appears to work immediately after the installation, but as soon as these temporary files are removed, it breaks. (It complains it cannot find `esgprep`.)

Manually moving the `.egg` directories into `site-packages` and editing the `easy-install.pth` file to change the directory from `/tmp/esg-publisher/src/python/esgcet/.eggs/` to `./` (the same as for the other existing packages) seems to fix it.

**Comment by alaniwi** [comment]
@soay

**Comment by soay** [comment]
Thanks for pointing that out, Alan. This should be an issue for installing the publisher with setup.py only but not for an "esg-node upgrade". If the requirements are added to both, install_requires and setup_requires the eggs are not correctly copied to the final path -- I'm not sure if this is an issue in python's setuptools. Anyway, the latest commit should fix it.
