### ISSUE TITLE
esgtest_publish timeouts on final Solr check

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#50]
Just checking the unpublishing step:

> Unpublish dataset
> Running "esgunpublish --project test --database-delete --map /tmp/test.1490743457.map --keep-credentials"... [OK]
> Check 1: Unpublished from Postgres... [OK]
> Check 2: Unpublished from THREDDS... [OK]
> Check 3: Unpublished from Solr Index... . . . . . . . . . . .^C

I can confirm manually with requests that the dataset was indeed unpublished as so:

>>> res = requests.get("http://localhost/esg-search/search?project=test&format=application%2Fsolr%2Bjson")
>>> res
<Response [200]>
>>> obj = json.loads(res.text)
>>> obj
{u'facet_counts': {u'facet_heatmaps': {}, u'facet_fields': {}, u'facet_dates': {}, u'facet_intervals': {}, u'facet_ranges': {}, u'facet_queries': {}}, u'responseHeader': {u'status': 0, u'QTime': 314, u'params': {u'fq': [u'type:Dataset', u'project:"test"'], u'facet.mincount': u'1', u'rows': u'10', u'indent': u'true', u'echoParams': u'all', u'df': u'text', u'facet': u'true', u'facet.method': u'enum', u'shards': u'localhost/solr/datasets,pcmdi11.llnl.gov/solr/datasets,vesgint-idx.ipsl.upmc.fr/solr/datasets', u'q': u'*:*', u'start': u'0', u'wt': u'json', u'facet.sort': u'lex', u'qf': u'text', u'tie': u'0.01', u'facet.limit': u'-1', u'q.alt': u'*:*', u'fl': u'*,score'}}, u'response': {u'start': 0, u'maxScore': 0.0, u'numFound': 0, u'docs': []}}

**Comment by soay** [comment]
This is caused by the new delete/retract functionality that was not present when I created the test script. I have fixed it, please give it another try.

**Comment by sashakames** [comment]
All tests pass in latest v2.5.1
