### ISSUE TITLE
recording global_attribute information in ESGF

### ISSUE THREAD

**Issue by taylor13** [ESGF/esg-publisher#58]
As I understand it, when publishing a data set, the publisher can obtain information from the directory structure, from the .ini configuration file(s), and/or from the global attributes and record it in the ESGF catalog(s).  It appears to me that in the case of global attributes, the name of the ESGF entry is identical to the name of the global attribute (so, for example, in CMIP6 the "frequency" global attribute gets stored as "frequency" in ESGF).  

My understanding of the search is that each search facet is linked to one and only one catalog category, but the facet name can be different from the catalog name.  So, for example, in CMIP6 the "Time Frequency" facet gets its values from the "frequency" (not "time_frequency").   In CMIP5, however, "Time Frequency" comes from "time_frequency".  This inconsistency means, I think, that it will be difficult to search across both the CMIP5 and CMIP6 results.

To help maintain consistency across various projects, it would be helpful if the name of a  global_attribute could be modified when it is recorded by ESGF.  So, rather than just recording the list of attributes to extract (e.g., in CMIP6 the .ini file includes: extract_global_attrs = realm, frequency, product, nominal_resolution, source_type, grid, branch_method, source_id, table_id, variant_label, instiution_id), could we provide this list as pairs of values, providing both the global_attribute name and the new ESGF name?  For example, we might want to rename "frequency" as "time_frequency" and "source_id" as "model".

If we can do this, it might be best to cycle through the ESG names, and look for the global attribute name associated with it.  That way we could populate two different ESG names with the same global_attribute value.  For example, in CMIP6 we might want ESGF to record both "model" and "source"; they would be identical as found in the source_id global attribute (but having both would help with cross-projects searches).  In the .ini file for CMIP6, the list of information obtained from global attributes, would include the pairs:  ("source", "source_id"), ("model", "source_id") ("time_frequency", "frequency").  The second value in each pair is the global attribute.

There are also ways to make the search work across projects by modifying the search interface, but I'm guessing that would be more complicated.

**Comment by taylor13** [comment]
Note that PrePARE checks the global attributes and filenames for consistency with the CMIP6 CVs, but it doesn't check the directory structure.  Therefore I think we must whenever possible extract the information needed for the ESGF catalogs from the global attributes (as the first choice) and only if they aren't available there, obtain them from the directory structure.  Otherwise some values obtained from the directory will likely be wrong.

 At some point, if it's important, we should check that the directory structure is consistent with the global attributes.

**Comment by sashakames** [comment]
Checking the directory structure is part of the publishing workflow.  We use the same CV source as prepare so all should be consistent.

**Comment by taylor13** [comment]
OK so you will know that the elements in the directory structure are found in the CVs, but you won't know if they are correct (as they appear in the file global attributes).  Why do you prefer to use info. from the directory structure rather than from the global attributes?

**Comment by sashakames** [comment]
There is a bug in the cdfile implementation. It doesn't seem to load space-separated attribute values correctly.  We need to switch this to use cdms2
