### ISSUE TITLE
Change log_dir in build.xml

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esg-publisher#59]
The build.xml tries to create a log directory at /esg/logs when being built.  The mkdir commands fails due a permission issues, probably because the builds do not have to be run as the root user.

The logs are being captured in a buildlogs directory when the Publisher is built using the ESGF-build script.  So attempting to create the /esg/logs directory might be unnecessary.

**Comment by sashakames** [comment]
The publisher doesn't need to be built by the builder .
