### ISSUE TITLE
Change cmor table usage

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#63]
-Default behavior is to use the “master” branch.  Ignores whatever data_specs_version global attribute (this was the original behavior)
-If you need to publish to older specs, set it in esg.cmip6.ini, eg.:  data_specs_version = “01.00.15”
-We would welcome additional changes to the publisher to support additional behaviors such as a “mixed” checkout, but would have to be enabled via a config setting

**Comment by glevava** [comment]
I will work on it next week to allows the publisher to fetch:
- "CMOR tables" from CMOR github repository and checkout the appropriate tag following the data_specs_version.
- "CMIP6_CV" from the CMOR github master branch (most up-to-date version)
