### ISSUE TITLE
Update SSL Protocol Version

### ISSUE THREAD

**Issue by fgreg** [ESGF/esg-publisher#64]
The publisher is using TLSv1 protocol to connect for publishing:

https://github.com/ESGF/esg-publisher/blob/1d0443ac3ad46680480dfdcce2a664027e3ca74f/src/python/esgcet/esgcet/publish/hessianlib.py#L515

This should be updated to a more recent TLS version. Recommend changing it to [ssl.PROTOCOL_TLS](https://docs.python.org/2/library/ssl.html#ssl.PROTOCOL_TLS) instead.

FWIW, I locally changed the one line of code linked above to:

    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS)

and was able to successfully publish a test dataset.

**Comment by sashakames** [comment]
Perhaps switching to requests will solve this issue (see https://github.com/ESGF/esg-publisher/issues/76)
