### ISSUE TITLE
List all publisher dependencies in requirements.txt

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esg-publisher#73]
Right now, if not all CMIP6 dependencies are installed, running the publisher results in an error message about not finding the ESMF module.

I would suggest to always install all dependencies, by listing them in requirements.txt

**Comment by LucaCinquini** [comment]
Specifically this is the error I get when installing just the publisher with no additional dependencies:

root@4cfa3de8420e esgcet]# source ${CDAT_HOME}/bin/activate esgf-pub
(esgf-pub) [root@4cfa3de8420e esgcet]# esginitialize -c
Allow anonymous logging usage to help improve UV-CDAT(you can also set the environment variable UVCDAT_ANONYMOUS_LOG to yes or no)? [yes]/no: no
Traceback (most recent call last):
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/ESMF/interface/loadESMF.py", line 122, in <module>
    mode=ct.RTLD_GLOBAL)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libhdf5_hl.so.100: cannot open shared object file: No such file or directory
INFO       2017-11-16 13:28:53,741 Updating schema version directory to /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet-3.2.7-py2.7.egg/esgcet/schema_migration
INFO       2017-11-16 13:28:53,743 Upgrading schema to latest version. (This may take a while.)
INFO       2017-11-16 13:28:53,755 6 -> 7... 
INFO       2017-11-16 13:28:53,760 done
INFO       2017-11-16 13:28:53,760 7 -> 8... 
INFO       2017-11-16 13:28:53,767 done
INFO       2017-11-16 13:28:53,769 Initializing standard names ...
INFO       2017-11-16 13:28:56,267 Initializing projects, models, and experiments ...
INFO       2017-11-16 13:28:56,275 Adding model IPSL-CM5A-LR for project test
INFO       2017-11-16 13:28:56,278 Adding model ncar_ccsm3_0 for project test
INFO       2017-11-16 13:28:56,280 Adding model test for project test
INFO       2017-11-16 13:28:56,283 Adding experiment test_exp for project test

**Comment by sashakames** [comment]
c91ada8008 - but lets get a proper test before closing out
