### ISSUE TITLE
Gradually switch from Hessian to the REST API

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esg-publisher#74]
The REST API for the ESGF publishing services has been working for several years now, using a client such as wget. An example wget invocation is:

wget --no-check-certificate --ca-certificate ~/.globus/certificate-file  --certificate ~/.globus/certificate-file  --private-key ~/.globus/certificate-file  --verbose --post-data="uri=https://esgf-data.jpl.nasa.gov/thredds/catalog/esgcet/1/obs4mips.NASA-JPL.AIRS.hus.mon.v20110608.xml&metadataRepositoryType=THREDDS" https://my-node.esgf.org/esg-search/ws/harvest

I think we should support the server-side REST API, starting with making it an option (so that we don't immediately remove support for the working hessian).

**Comment by sashakames** [comment]
Update:  default now for esgpublish

esgunpublish needs some help to complete this.

**Comment by sashakames** [comment]
v3.4.4 completes this, and we continue to allow hessian with --hessian
