### ISSUE TITLE
publisher set permissions

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#85]
On new thredds catalog directories, they should be made world rx.

**Comment by alaniwi** [comment]
But they already are?

https://github.com/ESGF/esg-publisher/blob/master/src/python/esgcet/esgcet/publish/thredds.py#L1252

**Comment by alaniwi** [comment]
(Equivalent permanent link including commit ID 
https://github.com/ESGF/esg-publisher/blob/23fbb79aae64c8c14e5251e48a4366ec73f3be5a/src/python/esgcet/esgcet/publish/thredds.py#L1252 )

**Comment by sashakames** [comment]
This is broken.

**Comment by alaniwi** [comment]
What is it doing different from what it should?

**Comment by sashakames** [comment]
Not that I'm doubting here that you'd believe me, but can provide evidence (before and after publishing --thredds)

Look at 6 

pcmdi7 14:14:41 esgcet $ ls -trl
total 444
drwxr-xr-x 2 ames4  climate      69632 Dec 20 11:36 4
drwxr-xr-x 2 ames4  climate      69632 Dec 20 13:38 5
drwxrwxrwx 2 tomcat climate      65536 Jan 17 10:42 2
drwxrwxrwx 2 tomcat climate      69632 Jan 17 10:42 3
drwxrwxrwx 2 tomcat publication  65536 Jan 17 10:42 1
-rwxrwxrwx 1 tomcat publication 106977 Jan 18 11:27 catalog.xml


pcmdi7 14:19:37 esgcet $ ls -trl
total 768
drwxr-xr-x 2 ames4  climate      69632 Dec 20 11:36 4
drwxrwxrwx 2 tomcat climate      65536 Jan 17 10:42 2
drwxrwxrwx 2 tomcat climate      69632 Jan 17 10:42 3
drwxrwxrwx 2 tomcat publication  65536 Jan 17 10:42 1
drwxr-xr-x 2 ames4  climate      86016 Jan 18 14:16 5
drwxr-x--- 2 ames4  climate      45056 Jan 18 14:16 6
-rwxrwxrwx 1 tomcat publication 379721 Jan 18 14:16 catalog.xml

**Comment by alaniwi** [comment]
Okay, I am guessing that you are running it with `umask` set to `027`. Any mode specified in the `mkdir` call will still be subject to `umask`. I guess it wouldn't harm to put in an explicit `chmod` in order to accommodate a restrictive umask.

**Comment by alaniwi** [comment]
(Just realised that the code uses 0775 while the above example uses 0755, but I think the point is clear.)

**Comment by sashakames** [comment]
Will test when we have adequate number of datasets again to trigger a mkdir for thredds.

**Comment by sashakames** [comment]
Didn't have a problem with DC2
