### ISSUE TITLE
Unable to scan CORDEX data with latest release of publisher.

### ISSUE THREAD

**Issue by pchengi** [ESGF/esg-publisher#91]
Sasha, CORDEX data publication seems to be affected by the latest publisher update.
Project 'test' publishes fine, but I encounter this when trying to publish CORDEX data.
This behavior is seen in a fresh install of 2.6.0 devel (the test branch).
2.6.1 devel which has the previous version of publisher doesn't produce this behavior.

````
(esgf-pub) [root@esg-idx esgcet]# esgprep mapfile --project cordex /esg/data/datapool1/
Mapfile(s) generation: 100% | 1/1 files
Scan errors: 1 (see /esg/config/esgcet/esgprep-20180204-012940-7114.err)
(esgf-pub) [root@esg-idx esgcet]# cat /esg/config/esgcet/esgprep-20180204-012940-7114.err
ERROR      2018-02-04 01:29:40,862 /esg/data/datapool1/cordexdata/cordex/output/AFR-44/SMHI/CCCma-CanESM2/historical/r0i0p0/SMHI-RCA4/v1/fx/orog/v20130927/orog_AFR-44_CCCma-CanESM2_historical_r0i0p0_SMHI-RCA4_v1_fx.nc skipped
NoConfigOption: Option not found
<option: 'rcm_name_map'>
<section: 'project:cordex'>
<file: '/esg/config/esgcet/esg.cordex.ini'>
````

**Comment by pchengi** [comment]
I checked again and see that it seems to be an issue with esgprep; everything works fine with esgprep  v2.7.33 2018-16-01, but when bumped up to esgprep v2.7.35 2018-02-02, it seems to break for CORDEX. Haven't tested with other projects.

**Comment by sashakames** [comment]
Looks like this is an esgprep problem.   Please file your issue within the esgf-prepare repo.
