### ISSUE TITLE
esgpublish --thredds does RabbitMQ connection even if command line usage wrong

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esg-publisher#94]
An example command line consisting only of:
```
esgpublish --project cmip6 --test --thredds
```
prints a usage messge followed by lines describing an active RabbitMQ connection.

I think it ought to stop after printing the usage message. If the command syntax is incorrect, it should not perform any action other than this.

**Comment by alaniwi** [comment]
It also reports "Created PID connector" before the usage message is printed.

**Comment by sashakames** [comment]
This is corrected in the v4 beta
